### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by lunkwill42** [arugifa/europython-2018-workshop#14]
ATM, there is a bug in `apistar` that prevents this from working under Python 3.7.

The bug report is here: https://github.com/encode/apistar/issues/595
There's an unmerged pull request with a fix here: https://github.com/encode/apistar/pull/598

The workshop code will function on Python 3.7 if `apistar` in `requirements.txt` is replaced with this:
`git+git://github.com/alkovpro/apistar@python37-issubclass-fix`

**Comment by arugifa** [comment]
Good to know 👍 Thanks :)

**Comment by arugifa** [comment]
As APIStar is not maintained anymore, I will probably replace it with Flask, next time I organize this workshop :)
