### ISSUE TITLE
Running tests does not work in "Set-up development environment" commit

### ISSUE THREAD

**Issue by stefreak** [arugifa/europython-2018-workshop#3]
tests to reproduce:

```
$ virtualenv venv
$ . venv/bin/activate
$ pip install -r requirements-text.txt
$ pytest
```

The error message is: `ModuleNotFoundError: No module named 'europython'`

Workaround: `PYTHONPATH="." pytest`

**Comment by arugifa** [comment]
We should run test with ``python -m pytest`` at this stage.

When running tests with Invoke afterwards, or directly into Docker, Tox will install the ``europython``'s package in the virtual environment, and Pytest will find the ``europython`` module.
