### ISSUE TITLE
README: Add basic guide how to set up dependencies for most common platforms

### ISSUE THREAD

**Issue by stefreak** [arugifa/europython-2018-workshop#6]

**Comment by stefreak** [comment]
dependencies
     -> python3.6
     -> docker
     -> docker-compose
     -> invoke, virtualenv, tox
     -> google chrome

**Comment by stefreak** [comment]
chromedriver as well

**Comment by arugifa** [comment]
Instead of writing some doc, a Vagrantfile has been made available instead, so people can set-up their working environment with a couple of commands.
